### ISSUE TITLE
Filtering output

### ISSUE THREAD

**Issue by thmsnhl** [jagr-co/amplify-nuxt#5]
Thank you for this tutorial it is a huge help ❤️ 

Maybe this is not the scope of your tutorial but it would be nice to have an example on how to filter the data coming from the graphql endpoint. 

For example, you could create a page for an author that lists all the posts, that have been created by a specific user or the current authenticated one.

**Comment by tomgobich** [comment]
My pleasure!

Yeah, I kind of jumped over filtering due to the length of the API videos. I'll circle back and cover this as well, thank you!
